### ISSUE TITLE
Support index file relationship in dataservice

### ISSUE THREAD

**Issue by junjun-zhang** [kids-first/kf-api-dataservice#328]
There is a need to maintain explicit relationship between data file and its index file. When listing files, only main data files should be returned with each has a record of its corresponding index file.

**Comment by allisonheath** [comment]
Two ideas have come up since then:

1) Rely on consistency of naming of CRAM/CRAI (or BAM/BAI - but will just use CRAM/CRAI for ease below) files. For example if from the dataservice you got back: `s3://kf-study-us-east-1-prd-sd-9pyzahhe/harmonized/cram/00025011-9dd7-40a6-8141-853323885e61.cram` you could assume that `s3://kf-study-us-east-1-prd-sd-9pyzahhe/harmonized/cram/00025011-9dd7-40a6-8141-853323885e61.cram.crai` exists. To actually be usable, this means that the `crai` file would need to be set to fully public. Policy-wise, this is fine because there's no identifiable data in the `crai`, just byte index information to the `cram`. Process-wise though, it introduces some risk as nothing is set to fully public at the moment in production buckets. One idea would be to change the prefix as well consistently so: `s3://kf-study-us-east-1-prd-sd-9pyzahhe/harmonized/crai/00025011-9dd7-40a6-8141-853323885e61.cram.crai`

2) Use the Gen3 "metadata" field to place the location of the `crai` for `cram` files.
