### ISSUE TITLE
Don't cascade delete files

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-dataservice#375]
To maintain 1-1 consistency with indexd, we should avoid deleting GenomicFiles and StudyFiles via cascades. These files are often 1-1 with S3, too, so deleting them will often be followed by a re-import of the same file with same `kf_id`, making the deletion often unnecessary in the first place.

**Comment by fiendish** [comment]
IMO, this is wrong. The problem isn't with deleting GFs and SFs. Those _should_ be removed.
The problem is that deleting those things shouldn't also delete entries from indexd. 

Indexd is meant to be a persistent record of file locations, which has nothing to do with what the dataservice db says at a particular moment. As long as a file exists somewhere in the world, its indexd record should persist indefinitely. We should be able to remove entries from the dataservice all day long without impacting that.
