### ISSUE TITLE
Suggestions on expanding identifier space

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#431]
Several different threads have been talking about how with some of the large count entities, such as phenotypes, diagnosis and files we're starting to feel cramped in our identifier space. Chances of collision are getting higher and even with suggestions like #423 there's potential to start having to do a lot of retries to get an ID. 

Two initial strategies to discuss (other ideas welcome) would be:

1) To uniformly expand the identifier space across all entities. E.g similar style but longer identifiers and/or something similar like https://github.com/ulid/spec.

2) To selectively expand identifier space for entities with large numbers, e.g. Files, Phenotypes and Diagnoses could use UUID4, especially because for phenotypes and diagnoses users don't typically have any use for specific identifiers for those.

**Comment by dankolbman** [comment]
Option 2 sounds pretty good so we can keep tidy ids on the high-vis entities like participants, studies, and biospecimens.

We should also consider refactoring our diagnoses/phenotype models as that could help reduce their number considerably. Right now we have events denormalized with the phenotype. We could improve quality and mapping consistency by normalizing the phenotype/diagnoses with their ontology ids out from the events/source text/timestamp data. This would also be helpful in establishing an temporally focused model.

**Comment by fiendish** [comment]
My preference would be to not generate IDs randomly at all since they're all coming from a central arbiter and could just be an incrementing counter. I don't see any benefit for the dataservice to have nonsequential identifiers.

Random ID generation exists to solve problems that we don't have (distributed simultaneous ID generation with unknown initial states) while introducing problems for scenarios that we do have (accidental reuse).

Of the two options presented above, I would vote for option 1 using ULID or something like it across the board, because I don't favor fragmentation and because, if you ignore how much of its bit-space is wasted on all of the times when entities are not being created, it basically acts like a complicated incrementer. For the sake of biospecimens that have been embedded inside genomic files (😭) we would need to still interoperate with the old style.
