### ISSUE TITLE
Add field to capture the DUO code to Biospecimen

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#541]
The value is an ontology code defined: https://github.com/EBISPOT/DUO

Not sure if we want it to be `duo_id` or `duo_id_biospecimen` to match other ontology fields?

**Comment by znatty22** [comment]
@allisonheath Should this field be the DUO ID (e.g. DUO:0000021) or the DUO shorthand code (e.g. IRB)? See: https://github.com/EBISPOT/DUO/blob/master/src/ontology/duo.csv

**Comment by znatty22** [comment]
Also, is this field replacing the `dbgap_consent_code` field we already have? See https://github.com/kids-first/kf-api-dataservice/blob/5d52f76e94097528360a08e99230a04d68bc865d/dataservice/api/biospecimen/models.py#L109

**Comment by baileyckelly** [comment]
I dont think the dbgap consent code would go away (at least not right now). That is where we store the code that we get directly from dbgap xml when we run the ACL tool. The dbgap consent codes map to the Consent Types - which can be specific to the study. However, the dbgap consent types would map to a more general DUO code perhaps?

Take the Marazita Orofacial cleft study. They have the following consent types:

- Health/Medical/Biomedical (MDS)
-- Consent Type Code: HMB-MDS
-- dbgap Consent Code: c4
-- Potential Duo Code: DUO:0000006 / HMB
- Disease-Specific (Orofacial birth defects and related phenotypes, MDS)
-- Consent Type Code: DS-OBDR-MDS
-- dbgap Consent Code: c1
-- Potential Duo Code: DS / disease specific research
- Disease-Specific (Orofacial birth defects, MDS)
-- Consent Type Code: DS-OBD-MDS
-- dbgap Consent Code: c2
-- Potential Duo Code: DS / disease specific research
- Disease-Specific (Oral Clefts, PUB, MDS)
-- Consent Type Code: DS-OC-PUB-MDS
-- dbgap Consent Code: c3
-- Potential Duo Code: DS / disease specific research AND DUO:0000019	PUB
- General Research Use
-- Consent Type Code: GRU
-- dbgap Consent Code: c5
-- Potential Duo Code: DUO:0000042 / GRU

Thoughts @allisonheath ?

**Comment by baileyckelly** [comment]
@znatty22 Note that one of the consent groups can have multiple DUO codes I think. The DS-OC-PUB-MDS is Disease Specific + Publication required. Not sure if we dash the codes like dbgap does or if we have to make this a one to many relationship.

**Comment by znatty22** [comment]
> can have multiple DUO codes I think

Ohh hmm, then that changes things. If this is true, then we'd have to either make `duo_id_biospecimen` an array field or we'd have to make a separate table for duo codes and have a many to many relationship between it and the biospecimen table..

**Comment by baileyckelly** [comment]
One other thing I'm noticing - the 3 disease specific consent types for Marazita allow for Methods Research (I believe thats the MDS at the end of the consent).  I dont see a DUO code for methods research...

**Comment by allisonheath** [comment]
We'll be working out the actual codes collaboratively as part of the NIH interop follow up, but yes expect there to be more than one. And it should contain the actual ontology ID (e.g. DUO:0000021).

**Comment by znatty22** [comment]
So we can implement this in a couple of ways, but I'm not sure which is the best. 

**Option 1:** Create a new array/list type attribute on biospecimen called duo_ids

**Pros**
- When you query/request for biospecimens you get back duo_ids without the need for additional join/request because the duo_ids attribute is on the biospecimen table itself
- Don’t need any extra tables to implement

**Cons**
- We need to implement custom query param parsing and filter logic so that someone can do the following:

`/biospecimens?duo_ids=duo_00001111,duo_00002222` - returns all specimens that have both duo_ids

cc @allisonheath  @baileyckelly  @dankolbman 

Thoughts? 👍or 👎 ?

**Comment by znatty22** [comment]
**Option 2:** Create a many-to-many relationship between biospecimen table and a duo_code table

**Pros**
- Can store additional info about the duo_code like the shorthand code, the description, etc.
- Don’t need to implement any custom logic or figure out anything new. Its just another m2m implementation

**Cons**
- Need 2 extra tables, along with all of the endpoints to implement (`/duo_codes`, `/biospecimen-duo-codes`, `/duo_codes?biospecimen_id`, `/biospecimens?duo_code_id`)
- If you want to query/request for biospecimen info including the duo_code_ids, you’d have to make multiple requests

cc @allisonheath  @baileyckelly  @dankolbman 

Thoughts? 👍or 👎 ?

**Comment by dankolbman** [comment]
Using arrays sounds like the easier short-term solution where as m2m is going to be more flexible long term.
The m2m may also cause some headache with all the network requests needed due to how we currently require manual creation of the relationships and the codes, though.

I think we can use a simple array with some validation and see if requirements come up that would make a m2m setup more appropriate.

**Comment by allisonheath** [comment]
Considering that after this quarter we might be looking at representing this information in a different way/service - I'd also suggest doing the easier short-term solution with arrays.

**Comment by allisonheath** [comment]
@znatty22 looks like this was done, but the issue didn't get closed?
