### ISSUE TITLE
New field for study code

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#547]
Right now for a study we have:
- `kf_id` (good for systems, not good for humans)
- `name` (often long, more like a paper title, not good for systems)
- `short_name` (shorter, but still not memorable, not good for systems)

None of these fit two increasing needs of:
1) Visual display on the portal, the graphs especially have gotten unwieldy with multiple studies, but also the main study facet

![Screen Shot 2019-11-06 at 9 11 54 AM](https://user-images.githubusercontent.com/2213854/68305337-8160cd80-0075-11ea-9f79-850f7135bd23.png)
 
2) Human reference when talking about studies, the study IDs we can't remember, names or investigator names often get mixed up

I had been a bit resistant to creating what felt like yet another identifier with a study code, as well as it has some implicit semantic meaning typically, but it now seems more like the right solution. So proposing we created a `study_code` field in data service on the study. Then we can generate TCGA/ICGC like codes for each e.g.:

`Kids First: Orofacial Cleft - European Ancestry` -> `KF-OFCE`
`Pediatric Brain Tumor Atlas: CBTTC ` -> `PBTA-CBTTC`

And then for those from other places that already have it, we can reuse those, e.g.
`TARGET: Neuroblastoma` -> `TARGET-NBL`

👍 👎 ?

**Comment by znatty22** [comment]
How are `short_name` and `name` used now on the portal? I guess I'm wondering more about `short_name`, can that be replaced with `study_code` or do we need both?

**Comment by allisonheath** [comment]
`short_name` is what's on the Y axis of the graph and in the main study facets:

<img width="381" alt="Screen Shot 2019-11-06 at 10 08 16 AM" src="https://user-images.githubusercontent.com/2213854/68310063-5f6b4900-007d-11ea-94be-e6cd7d8c2ad0.png">

What I could imagine is that `study_code` is displayed and then `short_name` could be used to hover over / more information, depending on the context. And then `name` would be the full title on say a study entity page (doesn't exist yet).

**Comment by znatty22** [comment]
@allisonheath 
- Is there a min/max char length requirement?
- Should this be a required attribute on study?

**Comment by allisonheath** [comment]
Let's go with six as the max length. And yes it should be required.

**Comment by znatty22** [comment]
@allisonheath Couple of questions ...
- How about min length - I'm thinking 3 or 4? Since this field is required people have to put in something and we probably don't want a code thats less than 3 or 4 chars right?

- Again since this is non-nullable field, I think the migration for this is going to need to include populating the `Study.study_code` column. Can I get a mapping of studies and study codes?

**Comment by znatty22** [comment]
@allisonheath @baileyckelly 

In order to close #550, the migration script needs the mapping of current study KF IDs to study codes. I made a [google sheet of all of the production studies](https://docs.google.com/spreadsheets/d/1KxkD0zbII1cYCDTnr7sF0KxTs7D_0tE9gEFSNFW8ya8/edit?usp=sharing). Please fill in the `study_code` column.
