### ISSUE TITLE
Create ID service/mechanism to assign kf_id's

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#7]
A standard should be defined for what a Kid's First id looks like and how it is generated.

**Comment by dankolbman** [comment]
We need to discuss the core set of ids and id formats that we assign to entities.
My thoughts are that each entity in our model should at least be assigned an kids-first id for general consumption. Something that indicates that it is the kids first id, the entity type, and the entity identity should be the minimum. For example:

A Person entity with `person_id: KF-PR000001`
An aliquot with `aliquot_id: KF-AL000001`

Another possibility is to namespace things by dataset and assign ids sequentially within. For example:

The first person in the Seidman dataset: `person_id: KF-SD-PR00001`
The twentieth sample in the Maris dataset: `sample_id: KF-MR-SA00001`

This has the upside of having more easily identifiable, comparable, and memorable ids, but would require every dataset to have a code assigned to it on submission.

Another option is to have internal ids in addition to the primary kids first id. These are only used for internal tracking and can be swapped around without users noticing.

**Comment by allisonheath** [comment]
Just for the record, I think every row (aka entity) should have:

`uuid` a uuid4 for the entity
`kf_id` a name spaced kids first ID as described above, I like the format `KF-<two/three letter abbreviation for the entity>-<short but random alphanumeric id>

I like random alphanumeric generation similar to (down right now): https://blog.datacite.org/cool-dois/. Which iirc creates a base64 hash and then does some small tweaks to remove characters like l10O to help with readability. It's implemented via: https://github.com/datacite/cirneco to create the DOI suffix. 

Both the `uuid` and `kf_id` can be used as primary keys within the Kids First space. The nice thing about UUIDs is that they can truly be used universally, are often easily consumed by other libraries/distribution systems. And if we get to the point where we have enough entities it's starting to cause collision issues, it would be easy to move over towards. It's a lightweight ask to prevent future headaches. 

Files might have to be handled as a special case, as depending on the different data types you can many files per Person. Additionally, right now Gen3 is the authoritative auth service so we need to have synchronized IDs. In Gen3 it's a UUID, so could consider either it's `kf_id` or make an explicit secondary id `dos_id` (that's for digital object schema - one of the GA4GH standards that Gen3 is participating in).  

Also, I foresee having a lot of different "external IDs" to map to, I think in general it's better to keep these in a separate service / tables rather than right with the Kids First entity.

**Comment by dankolbman** [comment]
Ok, for now we will assign the following ids to every entity:

- `id` - internal id from postgres
- `uuid` - `123e4567-e89b-12d3-a456-426655440000`
- `kf_id` - `123e4567` a [Crockford](http://www.crockford.com/wrmg/base32.html) base 32 encoded number between 0 and 32^8-1 with 0 padding to 8 characters.
